const loginFields = [
    {
        labelText: "email",
        labelFor: "email",
        id: "email",
        name: "email",
        type: "text",
        isRequired: true,
        placeholder: "indirizzo email o username",
    },
    {
        labelText: "Password",
        labelFor: "password",
        id: "password",
        name: "password",
        type: "password",
        isRequired: true,
        placeholder: "Password",
    },
];

const doctorFields = [
    {
        labelText: "nome",
        labelFor: "nome",
        id: "nome",
        name: "name",
        type: "text",
        isRequired: false,
        placeholder: "nome",
    },
    {
        labelText: "cognome",
        labelFor: "cognom",
        id: "cognome",
        name: "surname",
        type: "text",
        isRequired: false,
        placeholder: "cognome",
    },
    {
        labelText: "password",
        labelFor: "password",
        id: "password",
        name: "password",
        type: "text",
        isRequired: false,
        placeholder: "password",
    },
    {
        labelText: "email",
        labelFor: "email",
        id: "email",
        name: "email",
        type: "email",
        isRequired: false,
        placeholder: "email",
    },
    {
        labelText: "telefono",
        labelFor: "telefono",
        id: "telefono",
        name: "telefono",
        type: "text",
        isRequired: false,
        placeholder: "telefono",
    },
];
const patientFields = [
    {
        labelText: "nome",
        labelFor: "nome",
        id: "nome",
        name: "name",
        type: "text",
        isRequired: false,
        placeholder: "nome",
    },
    {
        labelText: "cognome",
        labelFor: "cognom",
        id: "cognome",
        name: "surname",
        type: "text",
        isRequired: false,
        placeholder: "cognome",
    },
    {
        labelText: "password",
        labelFor: "password",
        id: "password",
        name: "password",
        type: "text",
        isRequired: false,
        placeholder: "password",
    },
    {
        labelText: "email",
        labelFor: "email",
        id: "email",
        name: "email",
        type: "email",
        isRequired: false,
        placeholder: "email",
    },
    {
        labelText: "telefono",
        labelFor: "telefono",
        id: "telefono",
        name: "telefono",
        type: "text",
        isRequired: false,
        placeholder: "telefono",
    },
    {
        labelText: "dottore",
        labelFor: "dottore",
        id: "dottore",
        name: "doctor",
        type: "text",
        isRequired: false,
        placeholder: "dottore",
    },
];
export { loginFields, doctorFields, patientFields };
